[package]
name = "feeless_node"
version = "0.1.0"
authors = ["gak <gak@gak0.com>"]
edition = "2018"

[dependencies]
feeless = { path = "../core" }

tokio = { version = "*", features = ["full"] }
bitvec = "0.20.1"
anyhow = "1.0.38"